name: Update Changelog

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}

    - name: Set up Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Update Changelog
      env:
        GH_TOKEN: ${{ secrets.PAT }}
      run: |
        # Extract version from setup_auto_updates.sh
        NEW_VERSION=$(grep -oP '(?<=# Version: ).*' setup_auto_updates.sh)
        
        # Check if this version already has a tag
        if git rev-parse $NEW_VERSION >/dev/null 2>&1; then
          echo "Version $NEW_VERSION already tagged. Skipping changelog update."
          exit 0
        fi

        # Get the current date
        CURRENT_DATE=$(date "+%Y %b %d")
        
        # Get the latest commit message
        COMMIT_MSG=$(git log -1 --pretty=%B)
        
        # Check if the commit message starts with "//**" or is about updating the changelog
        if [[ $COMMIT_MSG =~ ^//\*\* || $COMMIT_MSG == "Update changelog for"* ]]; then
          echo "Skipping changelog update due to commit message."
          exit 0
        fi

        # Check if entry already exists and update README.md
        if ! grep -q "### .* - Version $NEW_VERSION" README.md; then
          sed -i "/^## Changelog/a \\\n### $CURRENT_DATE - Version $NEW_VERSION\n\n-- $COMMIT_MSG\n" README.md
          
          # Commit and push the updated README.md
          git add README.md
          git commit -m "Update changelog for $NEW_VERSION"
          git push https://$GH_TOKEN@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          
          # Create new tag
          git tag $NEW_VERSION
          git push https://$GH_TOKEN@github.com/${{ github.repository }}.git $NEW_VERSION
        else
          echo "Changelog entry for version $NEW_VERSION already exists. Skipping update."
        fi
